<?php
/**
 * CLI Installer for Business Website CMS
 *
 * Usage: php install.php
 *
 * Walks through: database setup, admin account creation,
 * basic site settings, and optional demo data import.
 */

if (php_sapi_name() !== 'cli') {
    http_response_code(403);
    echo 'This script must be run from the command line.';
    exit(1);
}

echo "\n";
echo "==============================================\n";
echo "  Business Website CMS — Installer\n";
echo "==============================================\n\n";

// Load .env if present
$envFile = __DIR__ . '/.env';
if (file_exists($envFile)) {
    $lines = file($envFile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    foreach ($lines as $line) {
        $line = trim($line);
        if ($line === '' || $line[0] === '#') continue;
        if (strpos($line, '=') === false) continue;
        [$key, $val] = explode('=', $line, 2);
        $key = trim($key);
        $val = trim($val);
        if (!getenv($key)) {
            putenv("$key=$val");
        }
    }
    echo "[OK] Loaded .env file\n";
}

// Step 1: Database configuration
echo "\n--- Database Configuration ---\n";
$dbHost = prompt('Database host', getenv('DB_HOST') ?: '127.0.0.1');
$dbPort = prompt('Database port', getenv('DB_PORT') ?: '3306');
$dbName = prompt('Database name', getenv('DB_NAME') ?: 'business_cms');
$dbUser = prompt('Database user', getenv('DB_USER') ?: 'root');
$dbPass = prompt('Database password', getenv('DB_PASS') ?: '', true);

// Test connection
echo "\nTesting database connection... ";
try {
    $dsn = "mysql:host=$dbHost;port=$dbPort;charset=utf8mb4";
    $pdo = new PDO($dsn, $dbUser, $dbPass);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    echo "Connected!\n";

    // Create database if it doesn't exist
    $pdo->exec("CREATE DATABASE IF NOT EXISTS `$dbName` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
    $pdo->exec("USE `$dbName`");
    echo "[OK] Database '$dbName' ready\n";
} catch (PDOException $e) {
    echo "FAILED\n";
    echo "Error: " . $e->getMessage() . "\n";
    exit(1);
}

// Write .env file
echo "\nWriting .env file... ";
$envContent = "# Generated by installer on " . date('Y-m-d H:i:s') . "\n";
$envContent .= "DB_HOST=$dbHost\n";
$envContent .= "DB_PORT=$dbPort\n";
$envContent .= "DB_NAME=$dbName\n";
$envContent .= "DB_USER=$dbUser\n";
$envContent .= "DB_PASS=$dbPass\n";
file_put_contents($envFile, $envContent);
echo "Done\n";

// Step 2: Run schema and migrations
echo "\nInitializing database schema... ";
putenv("DB_HOST=$dbHost");
putenv("DB_PORT=$dbPort");
putenv("DB_NAME=$dbName");
putenv("DB_USER=$dbUser");
putenv("DB_PASS=$dbPass");

require_once __DIR__ . '/config.php';
require_once __DIR__ . '/includes/functions.php';

// Force DB initialization by calling getDB
try {
    $db = getDB();
    echo "Done\n";
} catch (Exception $e) {
    echo "FAILED: " . $e->getMessage() . "\n";
    exit(1);
}

// Step 3: Admin account
echo "\n--- Admin Account ---\n";

// Check if any admin exists
$existingAdmin = $db->query('SELECT COUNT(*) FROM users')->fetchColumn();
if ($existingAdmin > 0) {
    echo "[INFO] Admin account(s) already exist. Skipping.\n";
} else {
    $adminUser = prompt('Admin username', 'admin');
    $adminPass = prompt('Admin password (min 8 chars)', '', true);
    while (strlen($adminPass) < 8) {
        echo "Password must be at least 8 characters.\n";
        $adminPass = prompt('Admin password', '', true);
    }

    $hash = password_hash($adminPass, PASSWORD_DEFAULT);
    $stmt = $db->prepare("INSERT INTO users (username, password_hash, role_id) VALUES (?, ?, 1)");
    $stmt->execute([$adminUser, $hash]);
    echo "[OK] Admin account created: $adminUser\n";
}

// Step 4: Site settings
echo "\n--- Site Settings ---\n";
$siteName = prompt('Company/Site name', 'My Business');
$siteEmail = prompt('Contact email', '');
$sitePhone = prompt('Contact phone', '');

updateSetting('company_name', $siteName);
if ($siteEmail) updateSetting('company_email', $siteEmail);
if ($sitePhone) updateSetting('company_phone', $sitePhone);
echo "[OK] Settings saved\n";

// Step 5: Optional demo data
echo "\n";
$loadDemo = strtolower(prompt('Load demo data? (sample products, pages, blog posts)', 'n'));
if ($loadDemo === 'y' || $loadDemo === 'yes') {
    $demoFile = __DIR__ . '/database/demo-data.php';
    if (file_exists($demoFile)) {
        $demoFn = require $demoFile;
        if (is_callable($demoFn)) {
            $demoFn($db);
        }
        echo "[OK] Demo data loaded\n";
    } else {
        echo "[SKIP] No demo data file found (database/demo-data.php)\n";
    }
}

// Step 6: Directory permissions
echo "\nChecking directory permissions... ";
$dirs = ['uploads/images', 'uploads/videos', 'uploads/downloads'];
foreach ($dirs as $dir) {
    $full = __DIR__ . '/' . $dir;
    if (!is_dir($full)) {
        mkdir($full, 0755, true);
    }
}
// Create backups directory outside document root
if (!is_dir(BACKUPS_PATH)) {
    mkdir(BACKUPS_PATH, 0755, true);
}
echo "Done\n";

// Done
echo "\n==============================================\n";
echo "  Installation Complete!\n";
echo "==============================================\n";
echo "\n";
echo "  Your site is ready. Open it in a browser:\n";
echo "    http://localhost:8080/\n";
echo "\n";
echo "  Admin panel:\n";
echo "    http://localhost:8080/admin/\n";
echo "\n";

// Helper function
function prompt(string $question, string $default = '', bool $hidden = false): string {
    $hint = $default !== '' && !$hidden ? " [$default]" : '';
    echo "$question$hint: ";

    if ($hidden && function_exists('readline')) {
        // Attempt to hide input on Unix
        if (strtoupper(substr(PHP_OS, 0, 3)) !== 'WIN') {
            system('stty -echo 2>/dev/null');
            $input = trim(fgets(STDIN));
            system('stty echo 2>/dev/null');
            echo "\n";
        } else {
            $input = trim(fgets(STDIN));
        }
    } else {
        $input = trim(fgets(STDIN));
    }

    return $input !== '' ? $input : $default;
}
